title: Homepage
description: Наш мобільний застосунок допомагає отримати лише перевірені новини, підібрані за  інтересами користувача, щоб він міг залишатися обізнаним без зайвого інформаційного шуму.
